kind: PersistentVolume
apiVersion: v1
metadata:
  name: ap-dags
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "LOCAL_DAG_FOLDER_PATH" # Update this

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ap-dags
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
